# Generated by Django 4.1.4 on 2022-12-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VolleyballTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('players', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=25)),
                ('cat_players', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='women.playerscategory')),
            ],
        ),
    ]
